#熔断器仪表盘
spring.application.name: hystrix-turbine
server.port: 8001
#监控哪些服务的应用在此处添加，隔开
turbine.appConfig: customer-demo
turbine.aggregator.clusterConfig: default
turbine.clusterNameExpression: new String("default")
#配置eureka地址
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/
turbine.instanceUrlSuffix.default: actuator/hystrix.stream
turbine.combine-host: true 